import { FeelingValue } from "@app/models/user.model";

export const EMOJI: FeelingValue[] = [
    { "id": "128512", "name": "Cười toe toét", "icon": "😀" },
      { "id": "128513", "name": "Cười há miệng, mắt to", "icon": "😃" },
      { "id": "128514", "name": "Cười mắt khép", "icon": "😄" },
      { "id": "128515", "name": "Cười mỉm", "icon": "😁" },
      { "id": "128516", "name": "Cười ngoác miệng", "icon": "😆" },
      { "id": "128517", "name": "Cười nghiêng đầu", "icon": "😅" },
      { "id": "128518", "name": "Cười hả hê", "icon": "😂" },
      { "id": "128519", "name": "Cười sung sướng", "icon": "🤣" },
      { "id": "128520", "name": "Mỉm cười", "icon": "😊" },
      { "id": "128521", "name": "Cười ngượng ngùng", "icon": "😳" },
      { "id": "128522", "name": "Cười với đôi mắt mơ màng", "icon": "😵" },
      { "id": "128523", "name": "Cười khúc khích", "icon": "😜" },
      { "id": "128524", "name": "Cười đểu", "icon": "😏" },
      { "id": "128525", "name": "Cười tươi", "icon": "😎" },
      { "id": '127867', "name": 'Tình bạn', "icon": '🍻' },
      { "id": '127873', "name": 'Ngày đặt biệt của tôi', "icon": '🎁' },
      { "id": '127877', "name": 'Ông già noel', "icon": '🎅' },
      { "id": '127876', "name": 'Cây thông giáng sinh', "icon": '🎄' },
      { "id": '127878', "name": 'Giao thừa', "icon": '🎆' },
      { "id": "128530", "name": "Chúc mừng", "icon": "🎉" },
      { "id": "128531", "name": "Mừng sinh nhật", "icon": "🎂" },
      { "id": "128532", "name": "Mừng thành công", "icon": "🏆" },
      { "id": "128533", "name": "Mừng chiến thắng", "icon": "🥇" },
      { "id": "128534", "name": "Mừng ngày cưới", "icon": "💍" },
      { "id": "128535", "name": "Mừng lễ tốt nghiệp", "icon": "🎓" },
      { "id": "128536", "name": "Mừng sự kiện đặc biệt", "icon": "🎊" },
      { "id": "128537", "name": "Mừng năm mới", "icon": "🎆" },
      { "id": "128538", "name": "Mừng kỷ niệm", "icon": "🎁" },
      { "id": "128539", "name": "Mừng lễ hội", "icon": "🪅" },
      { "id": "128540", "name": "Mừng thành tựu", "icon": "👏" },
      { "id": "128541", "name": "Mừng giải thưởng", "icon": "🥈" },
      { "id": "128542", "name": "Mừng sự kiện thể thao", "icon": "⚽" },
      { "id": "128543", "name": "Mừng lễ cưới", "icon": "💒" },
      { "id": "128544", "name": "Mừng thăng chức", "icon": "🎖️" },
      { "id": "128545", "name": "Mừng sự kiện ra mắt", "icon": "🚀" },
      { "id": "128548", "name": "Mừng đạt mục tiêu", "icon": "🎯" },
      { "id": "128549", "name": "Mừng lễ hội mùa thu", "icon": "🎃" },
      { "id": "128550", "name": "Mừng lễ hội mùa hè", "icon": "🌞" },
      { "id": "128551", "name": "Mừng kỳ nghỉ lễ", "icon": "🏖️" },
      { "id": "128552", "name": "Mừng kỷ niệm ngày làm việc", "icon": "📅" },
      { "id": "128553", "name": "Mừng ngày hội", "icon": "🕺" },
      { "id": "128554", "name": "Mừng thăng tiến", "icon": "🚀" },
      { "id": "128555", "name": "Mừng ngày vinh danh", "icon": "🌟" },
      { "id": "128556", "name": "Mừng đạt giải", "icon": "🏆" },
      { "id": "128557", "name": "Mừng hoàn thành thử thách", "icon": "🎯" },
      { "id": "128558", "name": "Mừng tốt nghiệp", "icon": "🎓" },
      { "id": "128559", "name": "Mừng các dịp lễ lớn", "icon": "🎆" }
];