import { DataSearchGroup } from "@app/models/search-group.model";
import { FeelingGroupValue, FeelingValue } from "@app/models/user.model";

export const INITIALIZE_FEELING_DATA: DataSearchGroup<FeelingValue>[] = [
  {
    id: 'GROUP01',
    groupName: 'Đang cảm thấy...',
    children: [
      { "id": "128512", "name": "Cười toe toét", "icon": "😀" },
      { "id": "128513", "name": "Cười há miệng, mắt to", "icon": "😃" },
      { "id": "128514", "name": "Cười mắt khép", "icon": "😄" },
      { "id": "128515", "name": "Cười mỉm", "icon": "😁" },
      { "id": "128516", "name": "Cười ngoác miệng", "icon": "😆" },
      { "id": "128517", "name": "Cười nghiêng đầu", "icon": "😅" },
      { "id": "128518", "name": "Cười hả hê", "icon": "😂" },
      { "id": "128519", "name": "Cười sung sướng", "icon": "🤣" },
      { "id": "128520", "name": "Mỉm cười", "icon": "😊" },
      { "id": "128521", "name": "Cười ngượng ngùng", "icon": "😳" },
      { "id": "128522", "name": "Cười với đôi mắt mơ màng", "icon": "😵" },
      { "id": "128523", "name": "Cười khúc khích", "icon": "😜" },
      { "id": "128524", "name": "Cười đểu", "icon": "😏" },
      { "id": "128525", "name": "Cười tươi", "icon": "😎" }
    ]
  },
  {
    id: 'GROUP02',
    groupName: 'Chúc mừng',
    children: [
      { id: '127867', name: 'Tình bạn', icon: '🍻' },
      { id: '127873', name: 'Ngày đặt biệt của tôi', icon: '🎁' },
      { id: '127877', name: 'Ông già noel', icon: '🎅' },
      { id: '127876', name: 'Cây thông giáng sinh', icon: '🎄' },
      { id: '127878', name: 'Giao thừa', icon: '🎆' },
      { "id": "128530", "name": "Chúc mừng", "icon": "🎉" },
      { "id": "128531", "name": "Mừng sinh nhật", "icon": "🎂" },
      { "id": "128532", "name": "Mừng thành công", "icon": "🏆" },
      { "id": "128533", "name": "Mừng chiến thắng", "icon": "🥇" },
      { "id": "128534", "name": "Mừng ngày cưới", "icon": "💍" },
      { "id": "128535", "name": "Mừng lễ tốt nghiệp", "icon": "🎓" },
      { "id": "128536", "name": "Mừng sự kiện đặc biệt", "icon": "🎊" },
      { "id": "128537", "name": "Mừng năm mới", "icon": "🎆" },
      { "id": "128538", "name": "Mừng kỷ niệm", "icon": "🎁" },
      { "id": "128539", "name": "Mừng lễ hội", "icon": "🪅" },
      { "id": "128540", "name": "Mừng thành tựu", "icon": "👏" },
      { "id": "128541", "name": "Mừng giải thưởng", "icon": "🥈" },
      { "id": "128542", "name": "Mừng sự kiện thể thao", "icon": "⚽" },
      { "id": "128543", "name": "Mừng lễ cưới", "icon": "💒" },
      { "id": "128544", "name": "Mừng thăng chức", "icon": "🎖️" },
      { "id": "128545", "name": "Mừng sự kiện ra mắt", "icon": "🚀" },
      { "id": "128546", "name": "Mừng thành công dự án", "icon": "🏅" },
      { "id": "128547", "name": "Mừng khám phá mới", "icon": "🌟" },
      { "id": "128548", "name": "Mừng đạt mục tiêu", "icon": "🎯" },
      { "id": "128549", "name": "Mừng lễ hội mùa thu", "icon": "🎃" },
      { "id": "128550", "name": "Mừng lễ hội mùa hè", "icon": "🌞" },
      { "id": "128551", "name": "Mừng kỳ nghỉ lễ", "icon": "🏖️" },
      { "id": "128552", "name": "Mừng kỷ niệm ngày làm việc", "icon": "📅" },
      { "id": "128553", "name": "Mừng ngày hội", "icon": "🕺" },
      { "id": "128554", "name": "Mừng thăng tiến", "icon": "🚀" },
      { "id": "128555", "name": "Mừng ngày vinh danh", "icon": "🌟" },
      { "id": "128556", "name": "Mừng đạt giải", "icon": "🏆" },
      { "id": "128557", "name": "Mừng hoàn thành thử thách", "icon": "🎯" },
      { "id": "128558", "name": "Mừng tốt nghiệp", "icon": "🎓" },
      { "id": "128559", "name": "Mừng các dịp lễ lớn", "icon": "🎆" }
    ]
  },
  {
    id: 'GROUP03',
    groupName: 'Đang chơi thể thao',
    children: [
      { id: 'children001', name: 'Bóng đá', icon: '⚽' },
      { id: '127992', name: 'Cầu lông', icon: '🏸' },
      { id: '127952', name: 'Bóng chuyền', icon: '🏐' },
      { id: '127936', name: 'Bóng rỗ', icon: '🏀' },
      { id: '127939', name: 'Chạy bộ', icon: '🏃' },
      { id: '127947', name: 'Cử tạ', icon: '🏋' },
      { id: '127918', name: 'Game', icon: '🎮' },
      { id: '127954', name: 'Golf', icon: '🏒' },
      { id: '127955', name: 'Bóng bàn', icon: '🏓' },
      { id: '127956', name: 'Leo núi', icon: '🏔' },
      { id: '127943', name: 'Cưỡi ngựa', icon: '🏇' },
      { id: '127946', name: 'Bơi lội', icon: '🏊' },
      { id: '127993', name: 'Bắn cung', icon: '🏹' },
      { id: '127935', name: 'Trượt băng', icon: '🎿' },
      { id: '129666', name: 'Dù lượn', icon: '🪂' },
      { id: '127907', name: 'Câu cá', icon: '🎣' },
    ]
  },  
  {
    id: 'GROUP04',
    groupName: 'Thời tiết',
    children: [
      { "id": "128680", "name": "Mặt trời", "icon": "☀️" },
      { "id": "128681", "name": "Mưa", "icon": "🌧️" },
      { "id": "128682", "name": "Mưa và cầu vồng", "icon": "🌦️" },
      { "id": "128683", "name": "Mưa bão", "icon": "🌩️" },
      { "id": "128684", "name": "Bão tuyết", "icon": "🌨️" },
      { "id": "128685", "name": "Bão", "icon": "🌪️" },
      { "id": "128686", "name": "Mặt trăng", "icon": "🌙" },
      { "id": "128687", "name": "Đám mây", "icon": "☁️" },
      { "id": "128688", "name": "Bão táp", "icon": "🌬️" },
      { "id": "128689", "name": "Nắng", "icon": "🌞" },
      { "id": "128690", "name": "Băng", "icon": "❄️" },
      { "id": "128691", "name": "Mưa nhẹ", "icon": "🌦️" },
      { "id": "128692", "name": "Mưa rào", "icon": "🌧️" },
      { "id": "128693", "name": "Cầu vồng", "icon": "🌈" },
      { "id": "128694", "name": "Mưa đá", "icon": "🌨️" },
      { "id": "128695", "name": "Bão tố", "icon": "🌪️" },
      { "id": "128696", "name": "Nắng ấm", "icon": "🌤️" },
      { "id": "128697", "name": "Nắng và mây", "icon": "⛅" },
      { "id": "128698", "name": "Lạnh", "icon": "🥶" },
      { "id": "128699", "name": "Nóng", "icon": "🥵" }
    ]    
  },
  {
    id: 'GROUP05',
    groupName: 'Du lịch',
    children: [
      { "id": "128640", "name": "Hành lý", "icon": "🧳" },
      { "id": "128641", "name": "Địa điểm du lịch", "icon": "🏖️" },
      { "id": "128642", "name": "Chuyến bay", "icon": "✈️" },
      { "id": "128643", "name": "Khách sạn", "icon": "🏨" },
      { "id": "128644", "name": "Chuyến tàu", "icon": "🚆" },
      { "id": "128645", "name": "Xe buýt", "icon": "🚌" },
      { "id": "128646", "name": "Ô tô", "icon": "🚗" },
      { "id": "128647", "name": "Taxi", "icon": "🚖" },
      { "id": "128648", "name": "Thẻ lên máy bay", "icon": "🎫" },
      { "id": "128649", "name": "Bản đồ", "icon": "🗺️" },
      { "id": "128650", "name": "Hộ chiếu", "icon": "🛂" },
      { "id": "128651", "name": "Hướng dẫn viên", "icon": "🗣️" },
      { "id": "128652", "name": "Kinh nghiệm", "icon": "🌏" },
      { "id": "128653", "name": "Quà lưu niệm", "icon": "🎁" },
      { "id": "128654", "name": "Sách hướng dẫn du lịch", "icon": "📖" },
      { "id": "128655", "name": "Bãi biển", "icon": "🏝️" },
      { "id": "128656", "name": "Địa điểm nổi tiếng", "icon": "🏛️" },
      { "id": "128657", "name": "Tháp Eiffel", "icon": "🗼" },
      { "id": "128658", "name": "Thuyền", "icon": "⛵" },
      { "id": "128659", "name": "Cáp treo", "icon": "🚡" },
      { "id": "128660", "name": "Lâu đài", "icon": "🏰" },
      { "id": "128661", "name": "Chợ", "icon": "🏪" },
      { "id": "128662", "name": "Khu vui chơi giải trí", "icon": "🎢" },
      { "id": "128663", "name": "Bãi đỗ xe", "icon": "🅿️" },
      { "id": "128664", "name": "Cảnh đẹp", "icon": "🏞️" },
      { "id": "128665", "name": "Bản đồ thành phố", "icon": "🏙️" },
      { "id": "128666", "name": "Chuyến đi", "icon": "🚢" },
      { "id": "128667", "name": "Lên máy bay", "icon": "🛫" },
      { "id": "128668", "name": "Hạ cánh", "icon": "🛬" },
      { "id": "128669", "name": "Giấy tờ tùy thân", "icon": "🪪" }
    ]
  },
  {
    id: 'GROUP06',
    groupName: 'Động vật',
    children: [
      { "id": "128580", "name": "Chó", "icon": "🐕" },
      { "id": "128581", "name": "Mèo", "icon": "🐈" },
      { "id": "128582", "name": "Ngựa", "icon": "🐎" },
      { "id": "128583", "name": "Voi", "icon": "🐘" },
      { "id": "128584", "name": "Gấu", "icon": "🐻" },
      { "id": "128585", "name": "Sư tử", "icon": "🦁" },
      { "id": "128586", "name": "Khỉ", "icon": "🐒" },
      { "id": "128587", "name": "Hươu cao cổ", "icon": "🦒" },
      { "id": "128588", "name": "Cáo", "icon": "🦊" },
      { "id": "128589", "name": "Thỏ", "icon": "🐇" },
      { "id": "128590", "name": "Chim", "icon": "🐦" },
      { "id": "128591", "name": "Gà", "icon": "🐔" },
      { "id": "128592", "name": "Bò", "icon": "🐄" },
      { "id": "128593", "name": "Dê", "icon": "🐐" },
      { "id": "128594", "name": "Cừu", "icon": "🐑" },
      { "id": "128595", "name": "Lợn", "icon": "🐖" },
      { "id": "128596", "name": "Rồng", "icon": "🐉" },
      { "id": "128597", "name": "Cá", "icon": "🐟" },
      { "id": "128598", "name": "Sò", "icon": "🐚" },
      { "id": "128599", "name": "Ốc", "icon": "🐌" },
      { "id": "128600", "name": "Chim cánh cụt", "icon": "🐧" },
      { "id": "128601", "name": "Đười ươi", "icon": "🦧" },
      { "id": "128602", "name": "Cá mập", "icon": "🦈" },
      { "id": "128603", "name": "Cá voi", "icon": "🐋" },
      { "id": "128604", "name": "Cá heo", "icon": "🐬" },
      { "id": "128605", "name": "Mực", "icon": "🦑" },
      { "id": "128606", "name": "Bướm", "icon": "🦋" },
      { "id": "128607", "name": "Côn trùng", "icon": "🐜" }
    ]
  },
  {
    id: 'GROUP07',
    groupName: 'Thực vật',
    children: [
      { "id": "128620", "name": "Cây xanh", "icon": "🌳" },
      { "id": "128621", "name": "Cây cọ", "icon": "🌴" },
      { "id": "128622", "name": "Cây thông", "icon": "🌲" },
      { "id": "128623", "name": "Cây bụi", "icon": "🌿" },
      { "id": "128624", "name": "Cây leo", "icon": "🍃" },
      { "id": "128625", "name": "Cây xương rồng", "icon": "🌵" },
      { "id": "128626", "name": "Hoa hồng", "icon": "🌹" },
      { "id": "128627", "name": "Hoa hướng dương", "icon": "🌻" },
      { "id": "128628", "name": "Hoa tulip", "icon": "🌷" },
      { "id": "128629", "name": "Hoa cúc", "icon": "🌼" },
      { "id": "128630", "name": "Hoa đinh hương", "icon": "🌸" },
      { "id": "128631", "name": "Hoa mẫu đơn", "icon": "🌺" },
      { "id": "128632", "name": "Hoa nhài", "icon": "🌸" },
      { "id": "128633", "name": "Rau diếp", "icon": "🥬" },
      { "id": "128634", "name": "Cà chua", "icon": "🍅" },
      { "id": "128635", "name": "Cà rốt", "icon": "🥕" },
      { "id": "128636", "name": "Ớt chuông", "icon": "🌶️" },
      { "id": "128637", "name": "Dưa hấu", "icon": "🍉" },
      { "id": "128638", "name": "Nho", "icon": "🍇" },
      { "id": "128639", "name": "Táo", "icon": "🍎" },
      { "id": "128640", "name": "Cam", "icon": "🍊" },
      { "id": "128641", "name": "Chuối", "icon": "🍌" },
      { "id": "128642", "name": "Dứa", "icon": "🍍" },
      { "id": "128643", "name": "Dâu tây", "icon": "🍓" },
      { "id": "128644", "name": "Quả bơ", "icon": "🥑" },
      { "id": "128645", "name": "Đậu", "icon": "🫘" }
    ]
  },
  {
    id: 'GROUP08',
    groupName: 'Khác',
    children: [
      { "id": "128580", "name": "Ngôi sao", "icon": "⭐" },
      { "id": "128581", "name": "Mặt trời", "icon": "☀️" },
      { "id": "128582", "name": "Mặt trăng", "icon": "🌙" },
      { "id": "128583", "name": "Đám mây", "icon": "☁️" },
      { "id": "128584", "name": "Bão", "icon": "🌪️" },
      { "id": "128585", "name": "Lửa", "icon": "🔥" },
      { "id": "128586", "name": "Nước", "icon": "💧" },
      { "id": "128587", "name": "Băng", "icon": "❄️" },
      { "id": "128588", "name": "Cầu vồng", "icon": "🌈" },
      { "id": "128589", "name": "Sấm sét", "icon": "⚡" },
      { "id": "128590", "name": "Đồng hồ", "icon": "🕰️" },
      { "id": "128591", "name": "Bóng đèn", "icon": "💡" },
      { "id": "128592", "name": "Điện thoại", "icon": "📱" },
      { "id": "128593", "name": "Máy tính", "icon": "💻" },
      { "id": "128594", "name": "TV", "icon": "📺" },
      { "id": "128595", "name": "Thư", "icon": "✉️" },
      { "id": "128596", "name": "Hộp quà", "icon": "🎁" },
      { "id": "128597", "name": "Tiền", "icon": "💵" },
      { "id": "128598", "name": "Bánh pizza", "icon": "🍕" },
      { "id": "128599", "name": "Hamburger", "icon": "🍔" },
      { "id": "128600", "name": "Đồ uống", "icon": "🍹" },
      { "id": "128601", "name": "Cà phê", "icon": "☕" },
      { "id": "128602", "name": "Bút chì", "icon": "✏️" },
      { "id": "128603", "name": "Sách", "icon": "📚" },
      { "id": "128604", "name": "Tài liệu", "icon": "📄" },
      { "id": "128605", "name": "Hộp đựng bút", "icon": "🖊️" },
      { "id": "128606", "name": "Hộp số", "icon": "📦" },
      { "id": "128607", "name": "Tấm thẻ", "icon": "🪪" },
      { "id": "128608", "name": "Bánh kem", "icon": "🍰" },
      { "id": "128609", "name": "Nón bảo hiểm", "icon": "⛑️" },
      { "id": "128610", "name": "Dấu chấm than", "icon": "❗" },
      { "id": "128611", "name": "Dấu hỏi", "icon": "❓" },
      { "id": "128612", "name": "Ngón tay chỉ lên", "icon": "☝" },
      { "id": "128613", "name": "Ngón tay cái lên", "icon": "👍" },
      { "id": "128614", "name": "Ngón tay cái xuống", "icon": "👎" },
      { "id": "128615", "name": "Lịch", "icon": "📅" },
      { "id": "128616", "name": "Đồng hồ đeo tay", "icon": "⌚" },
      { "id": "128617", "name": "Bản đồ thế giới", "icon": "🌍" },
      { "id": "128618", "name": "Ngôi nhà", "icon": "🏠" },
      { "id": "128619", "name": "Cửa hàng", "icon": "🏬" }
    ]
  }

]

